Feedback form
FindsTeam/Finds.Landing pull request #6
Opened 2018-07-27 18:15 UTC by ArtemDadychenko

Форма фидбека для получения данных от комьюнити

- [x] Подключить materializecss
- [x] Реализовать кнопку для вызова формы
- [x] Реализовать форму (реализована в виде sidenav)
- [x] Адаптировать под десктоп

2018-07-29 13:50 UTC, findscode requested changes

2018-07-29 13:50 UTC, GitStearis commented on css/map-page.css
> +#map {
Пожалуйста, не вешай на ID стили.

2018-07-29 13:50 UTC, GitStearis commented on map.html
> +  <meta name="description" content="Freebee - сервис-карта для помощи в поиске бесплатных возможностей вокруг.">
Думаю, все же "приложение-карта".

2018-07-30 20:53 UTC, ArtemDadychenko commented on map.html
> +  <meta name="description" content="Freebee - сервис-карта для помощи в поиске бесплатных возможностей вокруг.">
@GitStearis поправил

2018-07-30 20:56 UTC, ArtemDadychenko commented
@GitStearis плес, глянь вид, поправь или напиши фиксы, если будут

В целом фидбек уже готов, осталось только задеплоить бэк и клиента

2018-07-31 14:27 UTC, findscode requested changes

2018-07-31 14:27 UTC, GitStearis commented on map.html
> +              <div class="row">
Пожалуйста, сделай так, чтобы шрифт этих кнопок был такой же, как у кнопки "Нашли халяву"

2018-07-31 14:27 UTC, GitStearis commented on map.html
> +    <h5 class="sidebar-title">Поделитесь халявой с другими</h5>
Добавь "!" в конце.

2018-07-31 14:27 UTC, GitStearis commented on map.html
> +                <input id="feedback_address" placeholder="ул. Халявина, 7" type="text">
Расстояние между лейблами и инпутом очень сильно скачет на всей форме. Plz fix it.

2018-07-31 14:27 UTC, GitStearis commented on map.html
> +                <label for="feedback_description">Описание</label>
Добавь тут плейсхолдер, чтобы лейбл не был на его месте сразу.

2018-07-31 15:35 UTC, ArtemDadychenko commented on map.html
> +                <input id="feedback_address" placeholder="ул. Халявина, 7" type="text">
Дерьмо в chips, фиксанул на глазок

2018-08-01 21:13 UTC, merged